name: flutterboilerplate #TODO Replace with you app's name
description: My Flutter Boilerplate #TODO Replace with you app's description
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0
  dio_cache_interceptor: ^3.0.1
  firebase_crashlytics: ^2.2.1
  dio_firebase_performance: ^0.3.0
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  firebase_performance: ^0.7.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  freezed_annotation:
  json_serializable:
  package_info_plus: ^1.0.6
  pretty_dio_logger: ^1.1.1

dev_dependencies:
  build_runner: ^2.1.2
  # flutter packages pub run build_runner watch --delete-conflicting-outputs
  change_app_package_name: ^1.0.0
  # flutter pub run change_app_package_name:main <com.new.package.name>
  flutter_launcher_icons: ^0.9.2
  # flutter pub run flutter_launcher_icons:main
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.2.3
  # flutter pub run flutter_native_splash:create
  flutter_test:
    sdk: flutter
  #flutter_driver:
  #sdk: flutter
  freezed:
  # screenshots: ^2.1.1
  # screenshots
  test: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/splash.png


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - environments/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
